# Stub FindOpenGL for headless builds — the actual GL linking is done by logos-app at runtime
if(NOT TARGET OpenGL::GL)
    add_library(OpenGL::GL INTERFACE IMPORTED)
    # Point to the system libGL if it exists (runtime only)
    if(EXISTS "/usr/lib64/libGL.so.1")
        set_target_properties(OpenGL::GL PROPERTIES INTERFACE_LINK_LIBRARIES "/usr/lib64/libGL.so.1")
    endif()
endif()
if(NOT TARGET OpenGL::OpenGL)
    add_library(OpenGL::OpenGL INTERFACE IMPORTED)
    target_link_libraries(OpenGL::OpenGL INTERFACE OpenGL::GL)
endif()
set(OpenGL_FOUND TRUE)
set(OPENGL_FOUND TRUE)
set(OpenGL_GL_FOUND TRUE)
